"""country table

Revision ID: 3f06c7ee57b4
Revises: 9f4172e61ff0
Create Date: 2023-03-18 21:05:26.047150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f06c7ee57b4'
down_revision = '9f4172e61ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('artist', sa.Unicode(length=128), nullable=True),
    sa.Column('song', sa.Unicode(length=128), nullable=True),
    sa.Column('songUrl', sa.String(length=256), nullable=True),
    sa.Column('inFinal', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    op.drop_table('country')
    # ### end Alembic commands ###
