"""country_year_motherTongue_columns

Revision ID: 91259ce4028a
Revises: 94143f349d56
Create Date: 2023-05-02 18:59:39.514456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91259ce4028a'
down_revision = '94143f349d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('motherTongue', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('motherTongue')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
