"""review table

Revision ID: 94143f349d56
Revises: 3f06c7ee57b4
Create Date: 2023-03-20 17:18:30.071031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94143f349d56'
down_revision = '3f06c7ee57b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('countryId', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['countryId'], ['country.id'], name='countryId', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='userId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'countryId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
